'use strict';

var svgstore = require('svgstore');
var fs = require('fs');

var sprites = svgstore()
.add('weather_icons-01', fs.readFileSync('./src/svg/weather_icons-01.svg', 'utf8'))
.add('weather_icons-02', fs.readFileSync('./src/svg/weather_icons-02.svg', 'utf8'))
.add('weather_icons-03', fs.readFileSync('./src/svg/weather_icons-03.svg', 'utf8'))
.add('weather_icons-04', fs.readFileSync('./src/svg/weather_icons-04.svg', 'utf8'))
.add('weather_icons-05', fs.readFileSync('./src/svg/weather_icons-05.svg', 'utf8'))
.add('weather_icons-06', fs.readFileSync('./src/svg/weather_icons-06.svg', 'utf8'))
.add('weather_icons-07', fs.readFileSync('./src/svg/weather_icons-07.svg', 'utf8'))
.add('weather_icons-08', fs.readFileSync('./src/svg/weather_icons-08.svg', 'utf8'))
.add('weather_icons-09', fs.readFileSync('./src/svg/weather_icons-09.svg', 'utf8'))
.add('weather_icons-10', fs.readFileSync('./src/svg/weather_icons-10.svg', 'utf8'))
.add('weather_icons-11', fs.readFileSync('./src/svg/weather_icons-11.svg', 'utf8'))
.add('weather_icons-12', fs.readFileSync('./src/svg/weather_icons-12.svg', 'utf8'))
.add('weather_icons-13', fs.readFileSync('./src/svg/weather_icons-13.svg', 'utf8'))
.add('weather_icons-14', fs.readFileSync('./src/svg/weather_icons-14.svg', 'utf8'))
.add('weather_icons-15', fs.readFileSync('./src/svg/weather_icons-15.svg', 'utf8'))
.add('weather_icons-16', fs.readFileSync('./src/svg/weather_icons-16.svg', 'utf8'))
.add('weather_icons-17', fs.readFileSync('./src/svg/weather_icons-17.svg', 'utf8'))
.add('weather_icons-18', fs.readFileSync('./src/svg/weather_icons-18.svg', 'utf8'))
.add('weather_icons-19', fs.readFileSync('./src/svg/weather_icons-19.svg', 'utf8'))
.add('weather_icons-20', fs.readFileSync('./src/svg/weather_icons-20.svg', 'utf8'))
.add('weather_icons-21', fs.readFileSync('./src/svg/weather_icons-21.svg', 'utf8'))
.add('weather_icons-22', fs.readFileSync('./src/svg/weather_icons-22.svg', 'utf8'))
.add('weather_icons-23', fs.readFileSync('./src/svg/weather_icons-23.svg', 'utf8'))
.add('weather_icons-24', fs.readFileSync('./src/svg/weather_icons-24.svg', 'utf8'))
.add('weather_icons-25', fs.readFileSync('./src/svg/weather_icons-25.svg', 'utf8'))
.add('weather_icons-26', fs.readFileSync('./src/svg/weather_icons-26.svg', 'utf8'))
.add('weather_icons-27', fs.readFileSync('./src/svg/weather_icons-27.svg', 'utf8'))
.add('weather_icons-28', fs.readFileSync('./src/svg/weather_icons-28.svg', 'utf8'))
.add('weather_icons-29', fs.readFileSync('./src/svg/weather_icons-29.svg', 'utf8'))
.add('weather_icons-50', fs.readFileSync('./src/svg/weather_icons-30.svg', 'utf8'))
.add('weather_icons-31', fs.readFileSync('./src/svg/weather_icons-31.svg', 'utf8'))
.add('weather_icons-32', fs.readFileSync('./src/svg/weather_icons-32.svg', 'utf8'))
.add('weather_icons-33', fs.readFileSync('./src/svg/weather_icons-33.svg', 'utf8'))
.add('weather_icons-34', fs.readFileSync('./src/svg/weather_icons-34.svg', 'utf8'))
.add('weather_icons-35', fs.readFileSync('./src/svg/weather_icons-35.svg', 'utf8'))
.add('weather_icons-36', fs.readFileSync('./src/svg/weather_icons-36.svg', 'utf8'))
.add('weather_icons-37', fs.readFileSync('./src/svg/weather_icons-37.svg', 'utf8'))
.add('weather_icons-38', fs.readFileSync('./src/svg/weather_icons-38.svg', 'utf8'))
.add('weather_icons-39', fs.readFileSync('./src/svg/weather_icons-39.svg', 'utf8'))
.add('weather_icons-50', fs.readFileSync('./src/svg/weather_icons-40.svg', 'utf8'))
.add('weather_icons-41', fs.readFileSync('./src/svg/weather_icons-41.svg', 'utf8'))
.add('weather_icons-42', fs.readFileSync('./src/svg/weather_icons-42.svg', 'utf8'))
.add('weather_icons-43', fs.readFileSync('./src/svg/weather_icons-43.svg', 'utf8'))
.add('weather_icons-44', fs.readFileSync('./src/svg/weather_icons-44.svg', 'utf8'))
.add('weather_icons-45', fs.readFileSync('./src/svg/weather_icons-45.svg', 'utf8'))
.add('weather_icons-46', fs.readFileSync('./src/svg/weather_icons-46.svg', 'utf8'))
.add('weather_icons-47', fs.readFileSync('./src/svg/weather_icons-47.svg', 'utf8'))
.add('weather_icons-48', fs.readFileSync('./src/svg/weather_icons-48.svg', 'utf8'))
.add('weather_icons-49', fs.readFileSync('./src/svg/weather_icons-49.svg', 'utf8'))
.add('weather_icons-50', fs.readFileSync('./src/svg/weather_icons-50.svg', 'utf8'))
.add('weather_icons-51', fs.readFileSync('./src/svg/weather_icons-51.svg', 'utf8'))
.add('weather_icons-52', fs.readFileSync('./src/svg/weather_icons-52.svg', 'utf8'))
.add('weather_icons-53', fs.readFileSync('./src/svg/weather_icons-53.svg', 'utf8'))
.add('weather_icons-54', fs.readFileSync('./src/svg/weather_icons-54.svg', 'utf8'))
.add('weather_icons-55', fs.readFileSync('./src/svg/weather_icons-55.svg', 'utf8'))
.add('weather_icons-56', fs.readFileSync('./src/svg/weather_icons-56.svg', 'utf8'))
.add('weather_icons-57', fs.readFileSync('./src/svg/weather_icons-57.svg', 'utf8'))
.add('weather_icons-58', fs.readFileSync('./src/svg/weather_icons-58.svg', 'utf8'))
.add('weather_icons-59', fs.readFileSync('./src/svg/weather_icons-59.svg', 'utf8'))
.add('weather_icons-60', fs.readFileSync('./src/svg/weather_icons-60.svg', 'utf8'))
.add('weather_icons-61', fs.readFileSync('./src/svg/weather_icons-61.svg', 'utf8'))
.add('weather_icons-62', fs.readFileSync('./src/svg/weather_icons-62.svg', 'utf8'))
.add('weather_icons-63', fs.readFileSync('./src/svg/weather_icons-63.svg', 'utf8'))
.add('weather_icons-64', fs.readFileSync('./src/svg/weather_icons-64.svg', 'utf8'))
.add('weather_icons-65', fs.readFileSync('./src/svg/weather_icons-65.svg', 'utf8'))
.add('weather_icons-66', fs.readFileSync('./src/svg/weather_icons-66.svg', 'utf8'))
.add('weather_icons-67', fs.readFileSync('./src/svg/weather_icons-67.svg', 'utf8'))
.add('weather_icons-68', fs.readFileSync('./src/svg/weather_icons-68.svg', 'utf8'))
.add('weather_icons-69', fs.readFileSync('./src/svg/weather_icons-69.svg', 'utf8'))
.add('weather_icons-70', fs.readFileSync('./src/svg/weather_icons-70.svg', 'utf8'));

fs.writeFileSync('./public/sprites.svg', sprites);
